export const words = [
  ["actually", "aslında", "Actually, I prefer studying in the morning."], ["probably", "muhtemelen", "I will probably stay at home tonight."], ["available", "müsait", "Are you available after class?"], ["figure out", "çözmek / anlamak", "I am trying to figure out this question."], ["get along", "iyi anlaşmak", "I get along well with my classmates."], ["instead", "yerine", "Let’s walk instead of taking a taxi."], ["although", "-e rağmen", "Although I was tired, I studied."], ["quite", "oldukça", "This topic is quite interesting."], ["at least", "en azından", "At least I tried my best."], ["by the way", "bu arada", "By the way, how was your exam?"], ["it depends", "duruma bağlı", "It depends on the weather."], ["to be honest", "dürüst olmak gerekirse", "To be honest, I was nervous."],
  ["aware", "farkında", "I wasn't aware of the change."], ["avoid", "kaçınmak", "Try to avoid translating every word."], ["benefit", "fayda", "Speaking daily has a real benefit."], ["challenge", "zorluk", "This task is a challenge, but you can do it."], ["consider", "değerlendirmek", "Consider using a simpler sentence."], ["confident", "kendine güvenli", "She sounds confident when she speaks."], ["deal with", "başa çıkmak", "I need to deal with this problem calmly."], ["depend on", "bağlı olmak", "Success depends on regular practice."], ["encourage", "cesaretlendirmek", "My teacher encouraged me to speak."], ["expect", "beklemek", "Don't expect progress in one day."], ["improve", "geliştirmek", "Reading can improve your vocabulary."], ["manage", "başarmak / idare etmek", "I managed to finish the exercise."],
  ["notice", "fark etmek", "Did you notice the difference?"], ["opportunity", "fırsat", "Every conversation is an opportunity to learn."], ["prefer", "tercih etmek", "I prefer tea to coffee."], ["prepare", "hazırlanmak", "Prepare a few ideas before you speak."], ["realise", "farkına varmak", "I realised that I knew the answer."], ["recommend", "önermek", "I recommend practising aloud."], ["remind", "hatırlatmak", "Please remind me tomorrow."], ["require", "gerektirmek", "This level requires more practice."], ["seem", "görünmek", "The question seems difficult at first."], ["suggest", "önermek", "Can you suggest a film in English?"], ["support", "desteklemek", "Your examples support your opinion."], ["worry", "endişelenmek", "Don't worry about every small mistake."],
  ["make progress", "ilerleme kaydetmek", "You make progress when you practise often."], ["run out of", "tükenmek", "I ran out of time during the test."], ["look forward to", "dört gözle beklemek", "I look forward to hearing from you."], ["catch up", "arayı kapatmak", "I need to catch up with my homework."], ["bring up", "konu açmak", "She brought up an interesting idea."], ["come across", "rastlamak", "I came across a useful expression."], ["work out", "çözmek", "Let's work out the answer together."], ["take part", "katılmak", "Would you like to take part in the discussion?"], ["on the other hand", "öte yandan", "On the other hand, online learning is flexible."], ["as far as I know", "bildiğim kadarıyla", "As far as I know, the lesson starts at six."], ["in the end", "sonunda", "In the end, we found the right address."], ["for example", "örneğin", "For example, you can practise with a friend."],
  ["adapt", "uyum sağlamak", "It takes time to adapt to a new routine."], ["aim", "amaç / hedeflemek", "My aim is to speak more naturally."], ["approach", "yaklaşım", "Try a different approach to this exercise."], ["attend", "katılmak", "I attend the speaking club every Thursday."], ["behaviour", "davranış", "Small study habits can change your behaviour."], ["communicate", "iletişim kurmak", "English helps you communicate with new people."], ["curious", "meraklı", "Be curious about the words you hear."], ["effective", "etkili", "Short daily practice is often more effective."], ["habit", "alışkanlık", "Reading is a habit you can build slowly."], ["hesitate", "tereddüt etmek", "Do not hesitate to ask a question."], ["reliable", "güvenilir", "Choose a reliable source when you study."], ["worth", "değer", "Making mistakes is worth the effort if you learn from them."],
] as const;

export const abbreviations = [
  ["gonna", "going to", "Konuşma dilinde plan anlatırken duyulur; resmî yazıda kullanma."], ["wanna", "want to", "Hızlı ve gündelik konuşmada yaygındır."], ["gotta", "have got to / have to", "Zorunluluk için çok gündelik bir kısaltmadır."], ["kinda", "kind of", "Bir şeyi biraz belirsiz veya yumuşak anlatır."], ["IDK", "I don’t know", "Mesajlaşmada kullanılır; sesli konuşmada harf harf söyleyebilirsin."], ["BTW", "by the way", "Mesajlaşmada konu değiştirirken kullanılır."], ["TBH", "to be honest", "Mesajlaşmada dürüst bir fikre giriş yapar."], ["FYI", "for your information", "Bilgi paylaşırken kullanılır; resmî ton gerektirebilir."],
  ["IMO", "in my opinion", "Yazışmada kişisel görüş belirtir; resmî raporda tam biçmi kullan."], ["ASAP", "as soon as possible", "Acil ama nazik olmayan bir ton taşıyabilir."], ["BRB", "be right back", "Kısa süreliğine ayrılırken kullanılır."], ["OMG", "oh my gosh", "Samimi ve duygusal tepkiler için; iş e-postasında kullanma."], ["NGL", "not gonna lie", "Açık bir görüşten önce gelir; çok gündeliktir."], ["DM", "direct message", "Sosyal medya üzerinden özel mesaj demektir."], ["IRL", "in real life", "Çevrim içi dünya dışındaki yaşam için kullanılır."], ["TL;DR", "too long; didn't read", "Uzun metnin kısa özetinden önce kullanılır."], ["TMI", "too much information", "Fazla kişisel detay için esprili bir uyarıdır."], ["AFAIK", "as far as I know", "Emin olmadığın bilgiyi yumuşatır."], ["IKR", "I know, right?", "Karşı tarafla güçlü bir fikir birliği belirtir."], ["LMK", "let me know", "Cevap veya bilgi isterken kısa biçimdir."],
] as const;

export const contextualExercises = [
  { id: "context-available", word: "available", title: "Plan değişikliği", story: "Mina wants to meet her friend after class, but first she needs to check her schedule.", sentence: "Are you ___ after class today?", options: ["available", "instead", "actually"] },
  { id: "context-figure-out", word: "figure out", title: "Küçük bir gizem", story: "Arda cannot understand a difficult homework question, so he asks a classmate for help.", sentence: "Can you help me ___ this question?", options: ["get along", "figure out", "probably"] },
  { id: "context-instead", word: "instead", title: "Yağmurlu akşam", story: "The weather changes quickly. Two friends cancel their outdoor plan and choose a cosy alternative.", sentence: "Let's watch a film ___ of going out.", options: ["instead", "available", "although"] },
  { id: "context-aware", word: "aware", title: "Yeni kural", story: "The school changed the library timetable yesterday, but Ece did not see the announcement.", sentence: "I wasn't ___ of the new timetable.", options: ["aware", "confident", "available"] },
  { id: "context-manage", word: "manage", title: "Son dakika", story: "Kerem had a very busy day, but he finished his project before midnight.", sentence: "He ___ to finish the project on time.", options: ["managed", "noticed", "depended"] },
  { id: "context-opportunity", word: "opportunity", title: "Yeni kulüp", story: "A speaking club is opening at the university and students can meet people from different countries.", sentence: "It is a great ___ to practise English.", options: ["opportunity", "abbreviation", "decision"] },
  { id: "context-look-forward", word: "look forward to", title: "Güzel haber", story: "Zeynep's friend will visit next month and they have not seen each other for a long time.", sentence: "I really ___ seeing you next month.", options: ["look forward to", "run out of", "bring up"] },
  { id: "context-catch-up", word: "catch up", title: "Kaçırılan ders", story: "Ali was ill for three days and now he has several lessons to review.", sentence: "I need to ___ with the class.", options: ["catch up", "get along", "figure out"] },
  { id: "context-suggest", word: "suggest", title: "Film gecesi", story: "The group cannot decide what to watch, so Deniz offers an idea.", sentence: "Can you ___ a good comedy?", options: ["suggest", "avoid", "require"] },
  { id: "context-although", word: "although", title: "Kararlı öğrenci", story: "It was late and Sude was tired, but she still completed her practice.", sentence: "___ she was tired, she finished the practice.", options: ["Although", "Instead", "Probably"] },
  { id: "context-work-out", word: "work out", title: "Takım çalışması", story: "Two friends are trying different methods to solve a difficult puzzle.", sentence: "Let's ___ the answer together.", options: ["work out", "take part", "run out"] },
  { id: "context-remind", word: "remind", title: "Küçük not", story: "Aylin has an important appointment tomorrow and asks her friend for help.", sentence: "Please ___ me about the appointment.", options: ["remind", "support", "prepare"] },
] as const;
